ocftw/open-star-ter-village

webapp/packages/game/README.md
webapp/packages/game/src/index.ts
webapp/packages/game/src/types.d.ts

Before
```
PlayerState
|- workertokens
|- closedProjects
```
After
```
PlayerState
|- token
|   |- workers: number
|
|- completed
|- projects: Card.Project[]
```

[Refactor] rearrange token and completed project in player state

---

.github/workflows/build.yml

[Task](https://github.com/ocftw/open-star-ter-village/projects/2#card-75131614)
Add a simple build pipeline to listen to all push and pull request to main branch.

Feature: add build pipeline

---

webapp/client/src/App.css
webapp/client/src/App.test.tsx
webapp/client/src/App.tsx

Set a simple header and github link on page header

Feature: update home page wording and styling

---

webapp/client/src/BoardGame.tsx

Add rough player view to show player info for dev and debug

Feature: add rough player view

---

webapp/packages/game/src/deck.test.ts
webapp/packages/game/src/deck.ts
webapp/packages/game/src/index.ts

Bugfix to issue #7. Proposal: replace class with plain-object function factory.

Fix state is not serialisable

---

webapp/packages/game/README.md
webapp/packages/game/src/types.d.ts

Slot states records the current contribution points

Feature: add slot states in active project

---

webapp/client/src/BoardGame.tsx
webapp/packages/game/README.md
webapp/packages/game/src/index.ts
webapp/packages/game/src/types.d.ts

Based on #14
Validate and play project card from hand to table.

Feature: add basic create project move

---

webapp/packages/game/src/index.ts

Add basic recruit function

---

webapp/packages/game/src/index.ts

add basic contribution function

---

webapp/ROADMAP.md
webapp/packages/game/README.md
webapp/packages/game/src/index.ts
webapp/packages/game/src/types.d.ts

Major: 1. Add field action in player state. 2. Validate and deduct action tokens. 3. Validate and deduct worker tokens. 4. Refill action tokens in refill move

Feature: reduce action tokens and worker tokens in create project move

---

webapp/ROADMAP.md
webapp/packages/game/src/index.ts
webapp/packages/game/src/utils.test.ts
webapp/packages/game/src/utils.ts

based on #18 
Major:
1. play job card
2. deduct worker tokens
3. deduct action tokens
Minor:
- add zip helper inspired from python

Feature play job card, deduct worker and action tokens in recruit move

---

webapp/packages/game/src/index.ts

based on #19 
Major:
1. deduct action token in contribute move

Feature: deduct action token in contribute move

---

webapp/client/src/CurrentPlayer/CurrentPlayer.tsx
webapp/packages/game/src/index.ts
webapp/packages/game/src/types.d.ts

Based on #21 
Major:
Add follows features in refill-and-end move
1. refill project cards
2. refill resource cards

Feature: add refill and end

---

webapp/client/src/CurrentPlayer/CurrentPlayer.tsx
webapp/packages/game/src/index.ts
webapp/packages/game/src/types.d.ts

> Duplicate #22 but change the base branch to `main`
Based on #21 
Major:
Add follows features in refill-and-end move
1. refill project cards
2. refill resource cards

Feature: add refill and end (duplicate #22 )

---

README.md
ROADMAP.md

Add deploy heroku button on readme

doc(README): add deploy to heroku button

---

client/package.json
client/src/CurrentPlayer/CurrentPlayer.tsx
packages/game/package.json
packages/game/src/index.ts
packages/game/src/types.d.ts
server/package.json
yarn.lock

- chore(boardgame.io): update to the latest version
- refactor(types): collect all move functions into moves interface
- feat(webapp-client): add input boxes for poc testing
- fix(webapp-game): recruit should increase contributions
- refactor(webapp-game): rearrange active project init and update contribution logic
- refactor(webapp-game): decouple resourceCard name from update contribution

Fix: recruit should update contribution

---

packages/game/src/handCards.test.ts
packages/game/src/handCards.ts
packages/game/src/index.ts

- feat(webapp-game): add hand cards helper - get card by id
- refactor(webapp-game): replace hand card operations with helper methods
- refactor(webapp-game): add AddOne and RemoveOne for easily access hand card

refactor: replace operators with hand card helpers

---

client/src/CurrentPlayer/CurrentPlayer.tsx
packages/game/README.md
packages/game/src/activeProjects.test.ts
packages/game/src/activeProjects.ts
packages/game/src/handCards.test.ts
packages/game/src/handCards.ts
packages/game/src/index.ts
packages/game/src/types.d.ts

- feat(webapp-game): add accumulate contribution value when contribute
- feat(webapp-client): add simple contribute UI
- refactor(webapp-game): rename contribution state with byJob and bySlot for better naming
- feat(webapp-game): add worker slots to track player
- feat(webapp-game): add onwer to track project owner
- feat(webapp-game): add active projects helper - add project
- feat(webapp-game): add active projects helper - get project by id
- feat(webapp-game): add active project helper - contribute project
- feat(webapp-game): add active project helper - assign worker
- refactor(webapp-game): move off mock data from each test cases

feature: Add contribute button

---

client/src/CurrentPlayer/CurrentPlayer.tsx
packages/game/src/activeProjects.test.ts
packages/game/src/activeProjects.ts
packages/game/src/handCards.ts
packages/game/src/index.ts
packages/game/src/types.d.ts
packages/game/src/utils.test.ts
packages/game/src/utils.ts

- refactor(webapp-game): move filter inplace funtion off from handcards to utils
- feat(webapp-game): add threasholds field in the project card type
- feat(webapp-game): add filter fulfilled helper
- feat(webapp-game): add remove active project helper
- feat(webapp-game): add settle move
- feat(webapp-client): add settle move button

feat: add settle

---

client/src/App.css
client/src/App.tsx
client/src/BoardGame.tsx
client/src/CurrentPlayer/CurrentPlayer.tsx
client/src/Players/Players.tsx

- refactor(webapp-client): rearrange layout and styling

refactor: rearrange layout and styling

---

src/components/header.js
src/components/work.js

refactor(components): change Work title to 贊助者

---

src/components/imageAndText.jsx
src/pages/index.jsx

- feat(homepage): add home page example feature photos
- feat(homepage): add home page example boardgame photos

Add home page example photos

---

WEBAPP.md

`WEBAPP.md` has checked. Only base build path need to update.

Build script has move to project root

---

ROADMAP.md

Add tech improvement for Branch merging and Dependency upgrading.

doc(ROADMAP): add tech improvement roadmap

---

.github/pull_request_template.md

doc(github): add pull request template

---

homepage/README.md

update path description to clarify the onboarding process
- update path description 
N/A
N/A

Docs/update README.md

---

homepage/ROADMAP.md

Update roadmap about cms editor & website generation flow
- update roadmap doc
No UI change
No release

doc(homepage): update roadmap about cms editor & generation flow

---

homepage/.gitignore

Update gitignore.
- for ignore .yarn/install-state.gz
N/A
N/A

feat: update gitignore

---

homepage/package.json

Deploy method update from `export` to `hybrid`
- Move on from pure static generation site to hybrid mode
N/A
1m25s (w/ cached)
1m55s (w/ cached)

Refactor migrate deploy method from export to hybrid

---

homepage/next.config.js
homepage/src/components/banner.jsx
homepage/src/components/cardsColumns.jsx
homepage/src/components/imageAndText.jsx
homepage/src/components/logo.jsx
homepage/src/layouts/header.jsx

This reverts commit 424876f9e22ad3fd5224b4807b7c226859336540, reversing changes made to 82ff4de0813771b3313490e838841a6fd4d6e3bc.
The dev environment is always showing error. revert the code change

Revert "Merge pull request #103 from ocftw/feature/image-optimise"

---

homepage/next.config.js
homepage/src/components/cardsGrid.jsx
homepage/src/layouts/base.jsx
homepage/src/layouts/footer.jsx
homepage/src/layouts/header.jsx
homepage/src/pages/404.jsx
homepage/src/pages/_app.jsx
homepage/src/pages/_document.jsx
homepage/src/pages/campaign.jsx
homepage/src/pages/cards.jsx
homepage/src/pages/index.jsx

Please add the description of the changes here.
- Add Full version EN site
TO BE UPDATED
TO BE UPDATED
TO BE UPDATED
TO BE UPDATED
TO BE UPDATED
TO BE UPDATED

Feature EN Site

---

homepage/next.config.js
homepage/src/components/banner.jsx
homepage/src/components/logo.jsx
homepage/src/layouts/footer.jsx
homepage/src/layouts/header.jsx

Image optimisation on Header, Banner & Footer components
- Replace img tag w/ next/image component on header, banner & footer components
No UI change.
| item       | Before | After  |
| ---------- | ------ | ------ |
| w/ Cached  | 02m01s | 01m55s |
| item       | Before | After  |
| ---------- | ------ | ------ |
| Lighthouse | <img width="1393" alt="image" src="https://github.com/ocftw/open-star-ter-village/assets/1487883/996e2277-8ea6-4bb8-972c-be39395bc1cf"> | <img width="1392" alt="image" src="https://github.com/ocftw/open-star-ter-village/assets/1487883/845650e8-a6dd-4400-b58f-2c70f737bb70"> |

feature: image optimisation - header, banner, footer

---

homepage/_pages/en/index.md
homepage/_pages/zh-tw/index.md
homepage/src/pages/admin/config.json

- Add unique_slug field in Pages collection
- Update pages file
- Rename homepage file to be index
No UI update
N/A
N/A

feature: add unique slug in cms pages collection

---

homepage/_pages/en/resource.md
homepage/_pages/zh-tw/resource.md

Add resource.md for generator & editor
- Add empty resource.md w/ unique slug
N/A - no page generator yet
| item       | Before | After  |
| ---------- | ------ | ------ |
| w/ Cached  | 00m00s | 00m00s |
| w/o Cached | 00m00s | 00m00s |
| item       | Before | After  |
| ---------- | ------ | ------ |
| Lighthouse | img 1  | img 2  |

feat(homepage): add _pages/[lang]/resource.md

---

homepage/src/layouts/contentMapper.jsx

Section component should display image as shown in CMS preview
- pass image props to section component in content mapper.
| Scenarios  | Before | After |
| ---------- | ------ | ----- |
| Home Page | <img width="1840" alt="Screenshot 2023-09-26 at 11 34 21" src="https://github.com/ocftw/open-star-ter-village/assets/1487883/b97404a2-f952-44f2-add5-448a674256c9"> | <img width="1840" alt="Screenshot 2023-09-26 at 11 34 12" src="https://github.com/ocftw/open-star-ter-village/assets/1487883/8e877077-6e77-4a53-a4da-91e58798599f"> |
N/A

Section should display image

---

homepage/public/robots.txt
homepage/public/sitemap.xml

- update sitemap.xml and address sitemap into robotsx.txt
N/A
N/A

feat(homepage): update sitemap.xml and address sitemap into robots.txt

---

homepage/public/css/style.css
homepage/src/layouts/header.jsx

Add language dropdown menu in navigation bar
- Add language dropdown menu in navigation bar
Please attach screenshots of UI accordingly. If you don't have any UI changes, please remove this section.
| Scenarios  | Before | After |
| ---------- | ------ | ----- |
| Navigation Bar (desktop) | <img width="1840" alt="Screenshot 2566-10-13 at 16 43 58" src="https://github.com/ocftw/open-star-ter-village/assets/1487883/0c0dc2fd-1d31-4864-b811-7bcef5f776ca"> | <img width="1840" alt="Screenshot 2566-10-13 at 16 44 46" src="https://github.com/ocftw/open-star-ter-village/assets/1487883/ee2d1ca6-4d2d-4f24-bfbd-03c28d3bea9c"> |
| Navigation Bar (mobile) | <img width="1840" alt="Screenshot 2566-10-13 at 16 44 09" src="https://github.com/ocftw/open-star-ter-village/assets/1487883/5834b1ff-c89d-49eb-b906 …

feat(homepage): add i18n navigation dropdown

---

homepage/_pages/en/cards.md
homepage/_pages/en/index.md
homepage/_pages/en/resource.md
homepage/_pages/zh-tw/cards.md
homepage/_pages/zh-tw/index.md
homepage/_pages/zh-tw/resource.md
homepage/src/lib/getNavigationList.js
homepage/src/pages/admin/config.json

Fix page order in navigationList
- fix page order in navigationList
| Scenarios  | Before | After |
| ---------- | ------ | ----- |
| Rearrange | <img width="1125" alt="截圖 2023-10-23 18 49 32" src="https://github.com/ocftw/open-star-ter-village/assets/62057991/606973a9-bbbb-4fab-a36d-4fd3d58eb68d"> | <img width="1125" alt="截圖 2023-10-23 18 49 50" src="https://github.com/ocftw/open-star-ter-village/assets/62057991/62de89b5-023c-4cdc-98e7-1a42fc4ca569"> |

fix: fix page order in navigationList

---

homepage/_footer/zh-tw/footer.json

- fix(homepage): footer props rename
No UI impaction
| item       | Before | After  |
| ---------- | ------ | ------ |
| w/ Cached  | 00m00s | 00m00s |
| w/o Cached | 00m00s | 00m00s |

fix(homepage): footer props rename

---

homepage/public/css/style.css

This reverts commit 73239e5f78398cc91960b7c505fffa7d5eb1f7eb.
- Add back the orange underline
N/A
| item       | Before | After  |
| ---------- | ------ | ------ |
| w/ Cached  | 00m00s | 00m00s |
| w/o Cached | 00m00s | 00m00s |

Revert "fix(homepage): remove orange title underline"
